version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: omeka
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka
    volumes:
      - omeka-db:/var/lib/mysql
  omeka:
    depends_on:
      - db
    image: scbd/omeka
    restart: always
    volumes:
       - omeka-html:/var/www/html
    networks: 
      - websites
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:virtual-kiosk.cbd.int,omeka"      
      - "traefik.docker.network=websites"
volumes:
  omeka-html:
    external: true #force user to create its own volume with driver of his choice
  omeka-db:
    external: true #force user to create its own volume with driver of his choice
networks:
  default:
  websites:
    external:
      name: websites
